### PR TITLE
Fix issue 137 and 132

### PR DESCRIPTION
**Pull request by tantale**
Hi,

The purpose of this pull request in to fix the rendering of the `README.md` on PyPi (see issue #137 ) and the encoding problem described in issue #132.

- Always read the `README.md` file using utf-8 encoding,
- Add some "::" in the Markdown to make `README.md` file compatible with reStructuredText,
- Dinamicaly convert Markdown links to reStructuredText.

Note: The PR #136 is superseded by this one.

Regards,
– Laurent.

### CODE REVIEW

**Comment by bzm3r** [comment]
Any reason why this pull request is not yet merged?

**Comment by tantale** [comment]
IMO, @aerkalov has not enough time for this project: there are only [3 commits](https://github.com/aerkalov/ebooklib/commits/master) since Oct. 8, 2017. He should find trusted contributors and promote them to "Admin". He should hand over to someone…

Another thing: there are a master branch and several others that looks like feature [branches](https://github.com/aerkalov/ebooklib/branches/stale) -- which looks old -- and I don't see a "stable" or "develop" branch (see [git-flow](https://danielkummer.github.io/git-flow-cheatsheet/) cheatsheet). So, as an external contributor, it is difficult to separate bug fix from feature. So, Alex may be fearful to merge a pull request.

What a pity!

**Comment by bzm3r** [comment]
@tantale Would you be interested in making a fork of `ebooklib` with the latest fixes? Or, do you know of an alternative to this library?

**Comment by aerkalov** [comment]
If you check commit history you would see that merge request was accepted
just couple of days ago.  So it is not true that nothing is happening.
There are couple of PR dealing with utf8 in readme file which is pure ascii
for some time now. If you want you are free to fork it and continue or just
wait a day or two until i get to my laptop.

**Comment by aerkalov** [comment]
Merged this. Thanks for the PR. Will add you later to the AUTHORS.txt file.

**Comment by bzm3r** [comment]
@aerkalov thank you very much for merging this :)

**Comment by nmandalapu** [comment]
Guys
I apologize to randomly pollute your thread. I am pretty new to python. I have been trying to install textract package and I have the same trouble. Could you in simple terms let me know how to rectify this issue?
Regards
Narendra

**Comment by tantale** [comment]
This thread is about the rendering of the `README.md` file on [PyPi](https://pypi.python.org/pypi/EbookLib). [Textract](https://pypi.python.org/pypi/textract) doesn't seems to have this kind of problem.

You should consider posting your problem on [stackoverflow](https://stackoverflow.com/help/how-to-ask). Use the tag "Python".

**Pull request closed without merging**
