### PR TITLE
Fix: Some readers cannot click on links containing backslashes (\)

### PR DESCRIPTION
**Pull request by lemisky**
## Reader

https://www.wps.cn/

or

https://www.wps.com/

### Before repair

image

### After repair

image

### CODE REVIEW

**Comment by lemisky** [comment]
@aerkalov hello

**Comment by aerkalov** [comment]
What would be the code example you are using? I am curious what kind of names are you giving to the chapters?

I am asking because I don't think it is so much the issue of the library but rather of how you use it. Unicode characters, space and all other kind of characters should not be used for the file names inside of EPUB, just because some readers do not support it. I would say without really knowing how are you creating the EPUB.

**Comment by lemisky** [comment]
@aerkalov Hi author, sorry for forgetting to provide a code sample

> This is a meaningless example, purely for demonstration

```py
from ebooklib import epub

if __name__ == '__main__':
    epubook = epub.EpubBook()
    for i in range(1, 10):
        i = f'{i}' * i
        item = epub.EpubHtml(
            title=f'{i}', file_name=f'Text/{i}.xhtml',
            content=f'<h1>{i}</h1><p>{i}</p>'.encode('utf8')
        )
        epubook.add_item(item)
        epubook.spine.append(item)
        epubook.toc.append(epub.Link(item.file_name, item.title, item.file_name))

    nav = epub.EpubNav(file_name='nav.xhtml')
    epubook.add_item(nav)
    epubook.spine.insert(0, nav)
    epubook.toc.insert(0, epub.Link(nav.file_name, 'nav_title', 'content'))

    epubook.add_item(epub.EpubNcx())
    epub.write_epub('1.epub', epubook)
```

## The resulting epub file
[1.zip](https://github.com/aerkalov/ebooklib/files/10103886/1.zip)

image

**Comment by lemisky** [comment]
## But with this pr, everything will be normal

image

**Comment by topkie** [comment]
I also had this problem because on Windows, `os.path.relpath` returns the path separator as `\` instead of `/`

```
ERROR(RSC-020): G://comics//1.epub/EPUB/nav.xhtml(12,42): "text\chapter-1.xhtml" is not a valid URL (Backslash ("\") used as path segment delimiter)
```

**Comment by clach04** [comment]
Also fixes https://github.com/aerkalov/ebooklib/issues/284 ?

**Comment by clach04** [comment]
> @aerkalov Hi author, sorry for forgetting to provide a code sample
> 
> > This is a meaningless example, purely for demonstration
> 
> ```python
> from ebooklib import epub
> 
> if __name__ == '__main__':
>     epubook = epub.EpubBook()
>     for i in range(1, 10):
>         i = f'{i}' * i
>         item = epub.EpubHtml(
>             title=f'{i}', file_name=f'Text/{i}.xhtml',
>             content=f'<h1>{i}</h1><p>{i}</p>'.encode('utf8')
>         )
>         epubook.add_item(item)
>         epubook.spine.append(item)
>         epubook.toc.append(epub.Link(item.file_name, item.title, item.file_name))
> 
>     nav = epub.EpubNav(file_name='nav.xhtml')
>     epubook.add_item(nav)
>     epubook.spine.insert(0, nav)
>     epubook.toc.insert(0, epub.Link(nav.file_name, 'nav_title', 'content'))
> 
>     epubook.add_item(epub.EpubNcx())
>     epub.write_epub('1.epub', epubook)
> ```
> 
> ## The resulting epub file
> 
> [The resulting epub file 1.zip](https://github.com/aerkalov/ebooklib/files/10103886/1.zip)
> 
> image

Presumably this was ran on windows to generate the test book?

**Comment by aerkalov** [comment]
Thanks for this and I am not sure how I managed to miss the original post. Closing this and deploying the change which uses posixpath module rather than replace string.

**Pull request closed without merging**
